// export const ADD_INGREDIENT = 'ADD_INGREDIENT';
// export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
// export const SET_INGREDIENTS = 'SET_INGREDIENTS';
// export const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED';
// export const INIT_INGREDIENTS = 'INIT_INGREDIENTS';

export const SET_PRODUCTS = 'SET_PRODUCTS';
export const FETCH_PRODUCTS_FAILED = 'FETCH_PRODUCTS_FAILED';
export const TOGGLE_FAV = 'TOGGLE_FAV';

export const AUTH_USER = 'AUTH_USER';
export const AUTH_CHECK_STATE = 'AUTH_CHECK_STATE';
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_CHECK_TIMEOUT = 'AUTH_CHECK_TIMEOUT';
export const AUTH_INITIATE_LOGOUT = 'AUTH_INITIATE_LOGOUT';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';
