 export const REQUEST_API_DATA = "REQUEST_API_DATA";
export const RECEIVE_API_DATA = "RECEIVE_API_DATA";

export const REQUEST_FAVORITE = 'REQUEST_FAVORITE';
export const REQUEST_FAVORITE_START = 'REQUEST_FAVORITE_START';
export const REQUEST_FAVORITE_SUCCESS = 'REQUEST_FAVORITE_SUCCESS';
export const REQUEST_FAVORITE_FAIL = 'REQUEST_FAVORITE_FAIL';
export const REQUEST_INIT = 'REQUEST_INIT';

export const FETCH_FAVORITES_START = 'FETCH_FAVORITES_START';
export const FETCH_FAVORITES_SUCCESS = 'FETCH_FAVORITES_SUCCESS';
export const FETCH_FAVORITES_FAIL = 'FETCH_FAVORITES_FAIL';
export const FETCH_FAVORITES = 'FETCH_FAVORITES'

export const AUTH_USER = 'AUTH_USER';
export const AUTH_CHECK_STATE = 'AUTH_CHECK_STATE';
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_CHECK_TIMEOUT = 'AUTH_CHECK_TIMEOUT';
export const AUTH_INITIATE_LOGOUT = 'AUTH_INITIATE_LOGOUT';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';
